x-logging: &default-logging
  driver: "local"
  options:
    max-size: "20m"
    max-file: "5"

services:
  loan:
    platform: linux/x86_64
    build: .
    image: ags131/loan
    volumes:
      - ./data/loan:/data
      - ./data/storage:${OBJECT_STORAGE}
      - ./data/vk:/app/screeps_loan/static/vk
      - ./data/scanner:/app/screeps_loan/static/scanner
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000
    depends_on:
      postgres:
        condition: service_healthy
    logging: *default-logging

  scanner:
    platform: linux/x86_64
    image: ags131/sector-scanner
    build: sector-scanner
    volumes:
      - ./data/scanner:/app/data
    logging: *default-logging

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "screeps" ]
    ports:
      - 127.0.0.1:5432:5432
    logging: *default-logging

  # pgbackups:
  #   image: kartoza/pg-backup:14-3.2
  #   platform: linux/x86_64
  #   restart: always
  #   logging: *default-logging
  #   depends_on:
  #     - postgres
  #   environment:
  #       - POSTGRES_USER=${DB_USERNAME}
  #       - POSTGRES_PASS=${DB_PASSWORD}
  #       - POSTGRES_DB=${DB}
  #       - POSTGRES_HOST=postgres
  #   volumes:
  #       - ./data/backups:/backups
